import { nanoid } from "@reduxjs/toolkit";

export const workExperienceData = [
  {
    id: nanoid(),
    company: "Shein",
    position: "Training Specialist",
    duration: "08.2024 - current",
    responsibilities: [
      "Participating in daily meetings of operational and support departments to monitor progress and exchange key information.",
      "Conducting training sessions for management staff on the correction of subordinate working time records, department reassignment, and overtime reporting.",
      "Production and editing of video materials supporting training processes.",
      "Publishing training courses and certification exams on a dedicated e-learning platform.",
      "Responsibility for monitoring and maintaining training completion metrics across two dedicated locations.",
      "Translating created work instructions into English.",
    ],
  },
  {
    id: nanoid(),
    company: "Shein",
    position: "Senior Learning Coordinator",
    duration: "04.2024 - 08.2024",
    responsibilities: [
      "Creation and analysis of reports of results of new operators work quality and results of instructors work.",
      "Creation of new reports in order to meet company needs and analyze data (regarding trainings).",
      "Support launching new buildings.",
      "Creation of SOPs for new processes and implementation, validating new SOPs.",
      "Optimizing and updating training materials in response to dynamically changing operational needs, including safety regulations and quality guidelines",
    ],
  },
  {
    id: nanoid(),
    company: "Shein",
    position: "Learning Coordinator",
    duration: "02.2023 - 04.2024",
    responsibilities: [
      "Creating new training content.",
      "Daily cooperation with other departments.",
      "Keeping SOPs up to date.",
      "Validating new SOPs.",
      "Providing ondoarding trainings.",
      "Conducting trainings for empolyees, instructor training delivering.",
      "Researching for information to prepare trainings.",
    ],
  },
  {
    id: nanoid(),
    company: "Amazon",
    position: "Trainer WRO4",
    duration: "06.2022 - 02.2023",
    responsibilities: [
      "Cooperation with international subsidiaries to create new training content.",
      "Participation at Weekly Business Review meeting of European Region.",
      "Analysis and preparing weekly report of e-learning platform.",
      "Creating content of training materials.",
      "Controlling Safety Compliance indicators.",
      "Delivering onboarding training by Webex.",
      "Organization and coordination of training schedules.",
      "Work with the SharePoint and WorkDocs apps.",
      "Auditing Instructor's work.",
      "Creating monthly L&D newsletter.",
      "Creating surveys, tests according training materials",
    ],
  },
  {
    id: nanoid(),
    company: "Amazon",
    position: "Trainer WRO2",
    duration: "06.2020 - 06.2022",
    responsibilities: [
      "Education and training of new and experienced employees.",
      "Organization and coordination of training activities.",
      "Employee training and coaching.",
      "Support for cross-training of operational departments.",
      "Creating evaluations and analysis of results in Excel.",
      "Keeping SOPs up to date and validating new SOPs.",
      "Support in operational processes.",
      "Work with the training console and authorization management.",
      "Delivering Day0 training for New Hires.",
    ],
  },
  {
    id: nanoid(),
    company: "Royal Studio",
    position: "Beautician",
    duration: "03.2019 - 08.2020",
    responsibilities: [
      "Customer service by phone and in the salon.",
      "Making appointments.",
      "Performing classic, hybrid and gel manicure.",
      "Performing classic and hybrid pedicure.",
      "Performing cosmetic treatment.",
    ],
  },
  {
    id: nanoid(),
    company: "OVB Allfinanz",
    position: "Financial Advisor",
    duration: "11.2018 - 06.2019",
    responsibilities: [
      "Acquiring new customers.",
      "Analysis of customer needs.",
      "Improving advising skills.",
      "Participating in products trainings.",
      "Preparing solutions in line with customer needs.",
    ],
  },
  {
    id: nanoid(),
    company: "Cosnet",
    position: "Beautician - Trainer",
    duration: "09.2018 - 01.2019",
    responsibilities: [
      "Preparing invoices using the Subiekt GT program.",
      "Preparing dispatch notes.",
      "Organizing a training calendar and conducting trainings.",
      "Organizing business trips.",
      "Entering orders into the system.",
      "Completing and preparing orders for shipment.",
    ],
  },
  {
    id: nanoid(),
    company: "Pyszne.pl",
    position: "Sales Support Specialist",
    duration: "02.2018 - 09.2019",
    responsibilities: [
      "Verification of completeness of contracts.",
      "Entering contacts into the system.",
      "Verification of the correctness of data in the system.",
      "Archiving documents of restaurants.",
      "Activating restaurants on the portal.",
    ],
  },
  {
    id: nanoid(),
    company: "Pyszne.pl",
    position: "Customer Service Specialist",
    duration: "09.2014 - 01.2018",
    responsibilities: [
      "Delivering trainings of employees in the department of introducing delivery areas.",
      "Answering calls and emails from corporate clients and customers.",
      "Entering data into the system (menu and delivery areas valid in restaurants).",
      "Working under pressure of time and clients.",
      "Contact with the customers via phone and email.",
      "Order coordination.",
      "Controlling and improving quality of service.",
      "Work on the Sales Force platform.",
      "Delegating tasks to proper departments.",
    ],
  },
];
